version: '2'

services:
  db_dev:
    image: mysql
    ports:
      - "3306:3306"
    container_name: rails_app_dev
    environment:
      - MYSQL_ROOT_PASSWORD=75234963c13e0ac2d60015230e20b81c
      - MYSQL_DATABASE=rails_app
      - MYSQL_USER=rails_app_user
      - MYSQL_PASSWORD=rails_app_password
  db_test:
    image: mysql
    ports:
      - "3307:3306"
    container_name: rails_app_dev
    environment:
      - MYSQL_ROOT_PASSWORD=75234963c13e0ac2d60015230e20b81c
      - MYSQL_DATABASE=rails_app_test
      - MYSQL_USER=rails_app_user
      - MYSQL_PASSWORD=rails_app_password